version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "docker"
    directory: "/apps/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/api-gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/service-auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/service-core"
    schedule:
      interval: "weekly"
