version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      dev-dependencies:
        dependency-type: 'development'

  - package-ecosystem: 'docker'
    directory: '/apps/web'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker'
    directory: '/apps/api-gateway'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker'
    directory: '/apps/service-auth'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker'
    directory: '/apps/service-core'
    schedule:
      interval: 'monthly'
