packages:
  - 'apps/*'
  - 'packages/*'
injectWorkspacePackages: true
allowBuilds:
  '@apollo/protobufjs': false
  '@nestjs/core': false
  '@prisma/engines': false
  prisma: false
  protobufjs: false
  sharp: false
