apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  namespace: {{ include "observability.namespace" . }}
  labels:
    app.kubernetes.io/name: tempo
    {{- include "observability.labels" . | nindent 4 }}
spec:
  serviceName: tempo
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tempo
        {{- include "observability.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/tempo/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: tempo
          image: {{ .Values.tempo.image }}
          args:
            - '-config.file=/etc/tempo/tempo.yaml'
          ports:
            - name: http
              containerPort: 3200
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/tempo/tempo.yaml
              subPath: tempo.yaml
              readOnly: true
            - name: data
              mountPath: /var/tempo
          resources:
            requests:
              memory: {{ .Values.tempo.resources.requests.memory }}
              cpu: {{ .Values.tempo.resources.requests.cpu }}
            limits:
              memory: {{ .Values.tempo.resources.limits.memory }}
              cpu: {{ .Values.tempo.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: tempo-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.tempo.storage }}
