{{- $component := "redis" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $component }}
  namespace: {{ include "luckyplans.namespace" . }}
  labels:
    {{- include "luckyplans.componentLabels" (dict "component" $component "ctx" .) | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "luckyplans.selectorLabels" (dict "component" $component "ctx" .) | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: api-gateway
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: service-auth
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: service-core
      ports:
        - protocol: TCP
          port: 6379
