apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ include "observability.namespace" . }}
  labels:
    app.kubernetes.io/name: grafana
    {{- include "observability.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.{{ include "observability.namespace" . }}.svc:9090
        isDefault: true
        editable: false

      - name: Loki
        type: loki
        access: proxy
        url: http://loki.{{ include "observability.namespace" . }}.svc:3100
        editable: false
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '"traceId":"(\w+)"'
              name: TraceID
              url: '$${__value.raw}'

      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo.{{ include "observability.namespace" . }}.svc:3200
        editable: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            filterByTraceID: true
          serviceMap:
            datasourceUid: prometheus
