apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ include "observability.namespace" . }}
  labels:
    app.kubernetes.io/name: grafana
    {{- include "observability.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.grafana.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        {{- include "observability.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 472
        runAsNonRoot: true
        runAsUser: 472
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
            {{- if .Values.grafana.ingress.enabled }}
            - name: GF_SERVER_ROOT_URL
              value: 'https://{{ .Values.grafana.ingress.host }}/grafana/'
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: 'true'
            {{- end }}
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
              readOnly: true
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/provider.yaml
              subPath: provider.yaml
              readOnly: true
            - name: grafana-storage
              mountPath: /var/lib/grafana
          resources:
            requests:
              memory: {{ .Values.grafana.resources.requests.memory }}
              cpu: {{ .Values.grafana.resources.requests.cpu }}
            limits:
              memory: {{ .Values.grafana.resources.limits.memory }}
              cpu: {{ .Values.grafana.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: grafana-storage
          emptyDir: {}
