apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ include "observability.namespace" . }}
  labels:
    app.kubernetes.io/name: prometheus
    {{- include "observability.labels" . | nindent 4 }}
