apiVersion: v1
kind: ConfigMap
metadata:
  name: luckyplans-config
  namespace: {{ include "luckyplans.namespace" . }}
  labels: {{- include "luckyplans.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  API_GATEWAY_PORT: {{ .Values.config.apiGatewayPort | quote }}
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
