apiVersion: v1
kind: ConfigMap
metadata:
  name: luckyplans-config
  namespace: {{ include "luckyplans.namespace" . }}
  labels: {{- include "luckyplans.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  API_GATEWAY_PORT: {{ .Values.config.apiGatewayPort | quote }}
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
  KEYCLOAK_ISSUER: {{ .Values.config.keycloakIssuer | quote }}
  KEYCLOAK_JWKS_URI: {{ .Values.config.keycloakJwksUri | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.config.keycloakClientId | quote }}
  KEYCLOAK_ADMIN_URL: {{ .Values.config.keycloakAdminUrl | quote }}
  API_GATEWAY_URL: {{ .Values.config.apiGatewayUrl | quote }}
  SESSION_TTL_SECONDS: {{ .Values.config.sessionTtlSeconds | quote }}
  MINIO_ENDPOINT: {{ .Values.config.minioEndpoint | quote }}
  MINIO_PORT: {{ .Values.config.minioPort | quote }}
  MINIO_USE_SSL: {{ .Values.config.minioUseSSL | quote }}
  MINIO_BUCKET: {{ .Values.config.minioBucket | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelExporterEndpoint | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
