apiVersion: v1
kind: Secret
metadata:
  name: luckyplans-secrets
  namespace: {{ include "luckyplans.namespace" . }}
  labels:
    {{- include "luckyplans.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secrets }}
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- else }}
stringData: {}
{{- end }}
