apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: {{ include "observability.namespace" . }}
  labels:
    app.kubernetes.io/name: otel-collector
    {{- include "observability.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.otelCollector.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        {{- include "observability.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/otel-collector/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.otelCollector.image }}
          args:
            - '--config=/etc/otelcol-contrib/config.yaml'
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: prometheus
              containerPort: 8889
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol-contrib/config.yaml
              subPath: config.yaml
              readOnly: true
          resources:
            requests:
              memory: {{ .Values.otelCollector.resources.requests.memory }}
              cpu: {{ .Values.otelCollector.resources.requests.cpu }}
            limits:
              memory: {{ .Values.otelCollector.resources.limits.memory }}
              cpu: {{ .Values.otelCollector.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
