apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ include "observability.namespace" . }}
  labels:
    app.kubernetes.io/name: otel-collector
    {{- include "observability.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: prometheus
      port: 8889
      targetPort: 8889
      protocol: TCP
