{{- if .Values.redisExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: {{ include "observability.namespace" . }}
  labels:
    app.kubernetes.io/name: redis-exporter
    {{- include "observability.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis-exporter
  ports:
    - name: metrics
      port: 9121
      targetPort: 9121
      protocol: TCP
{{- end }}
