apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: {{ include "observability.namespace" . }}
  labels:
    app.kubernetes.io/name: loki
    {{- include "observability.labels" . | nindent 4 }}
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        {{- include "observability.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/loki/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          args:
            - '-config.file=/etc/loki/loki.yaml'
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki/loki.yaml
              subPath: loki.yaml
              readOnly: true
            - name: data
              mountPath: /loki
          resources:
            requests:
              memory: {{ .Values.loki.resources.requests.memory }}
              cpu: {{ .Values.loki.resources.requests.cpu }}
            limits:
              memory: {{ .Values.loki.resources.limits.memory }}
              cpu: {{ .Values.loki.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: loki-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.loki.storage }}
