apiVersion: v2
name: luckyplans
description: LuckyPlans platform — web, api-gateway, service-core, redis
type: application
version: 0.1.0
appVersion: '0.1.0'
keywords:
  - luckyplans
  - nextjs
  - nestjs
maintainers:
  - name: LuckyPlans Team
