apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: {{ include "observability.namespace" . }}
  labels:
    app.kubernetes.io/name: promtail
    {{- include "observability.labels" . | nindent 4 }}
