{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: {{ include "luckyplans.namespace" . }}
  labels:
    {{- include "luckyplans.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage | quote }}
{{- end }}
